### ISSUE TITLE
wavm-run not in VS solution

### ISSUE THREAD

**Issue by kungfooman** [WAVM/WAVM#146] opened 2019-03-19 15:33 UTC
Hi, I wondered which thingy actually executes a `.wasm` and then I realized it's not even in the solution. So I just copypasted `Programs\wavm-run\wavm-run.cpp` into the `Programs -> wavm-disas` project. The code seems to need a bunch of fixes by default: 

![image](https://user-images.githubusercontent.com/5236548/54618572-8845bc00-4a63-11e9-80ca-683b58a0f91d.png)

Most stuff can be fixed with this:

```C
#define RUNTIME_API
#define EMSCRIPTEN_API
```

And comment some unneeded thread stuff out. But then it produces lots of linker errors:

![image](https://user-images.githubusercontent.com/5236548/54618730-c8a53a00-4a63-11e9-98d4-44f1d0777d4f.png)

Would be nice if wavm-run works in VS2017 too.

**Comment by kungfooman** [comment] 2019-03-20 01:04
Just seen this, so this isn't so easy I guess: https://github.com/WAVM/WAVM/issues/116

**Comment by AndrewScheidecker** [comment] 2019-03-20 01:18
Yeah, `wavm-as` and `wavm-disas` should work fine on 32-bit platforms, but the runtime doesn't support 32-bit hosts.

**Comment by AndrewScheidecker** [comment] 2019-06-20 19:10
Closing this as a duplicate of #116.

**Closed by AndrewScheidecker** 2019-06-20 19:10 UTC
